import './globals.css'
export const metadata = {
  title: 'Filip | Fullstack Developer',
  description: 'Generated by create next app',
  icons: {
    icon: '../public/favicon.png'
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>{children}</body>
    </html>
  )
}
